server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        waitDuration: 1s
spring:
  application:
    name: bookservice
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console